### ISSUE TITLE
meta-learning on customized networks

### ISSUE THREAD

**Issue by buaaswf** [silverbottlep/meta_trackers#14]
Dear @silverbottlep ,
I am writing a meta-tracker on siamFC network, please give me some suggestions on the reproduce steps

Thank you so much,

**Comment by silverbottlep** [comment]
I do not know the details about siamFC, so, I don't think I can answer this. but good luck!

**Comment by buaaswf** [comment]
Hi @silverbottlep 
Thank you for your reply.
This is the network of siamfc,
https://github.com/huanglianghua/siamfc-pytorch/blob/master/siamfc.py
It is a siamese network for binary classification.
Besides, do you think https://github.com/AntreasAntoniou/HowToTrainYourMAMLPytorch will help?

Thank you very much for your help.
It is important to me.
