### ISSUE TITLE
inconsistent result with python 2.7

### ISSUE THREAD

**Issue by silverbottlep** [silverbottlep/meta_trackers#2]
Someone tried meta_crest with pre-trained model with python 2.7, he reported it gave different result. When he changed to python 3.5, he could reproduce the result. At this point, I have no idea, hopefully have a chance to look at it later. FYI, my environment was python 3.6, pytorch 0.2.0+3f6fccd.

**Comment by SMZCC** [comment]
Not only the meta_crest, but also the meta_sdnet is lower than the paper. :confused:
