### ISSUE TITLE
I have solved many bugs in the code!

### ISSUE THREAD

**Issue by zhengzhenxian** [silverbottlep/meta_trackers#4]
Great job!
1.the mat file is not imagenet-vgg-verydeep-16.mat  but the imagenet-vgg-m.mat, you can download in
http://www.vlfeat.org/matconvnet/models/imagenet-vgg-m.mat

2. The cpu version doesn't work, so GPU is necessary for you!

**Comment by silverbottlep** [comment]
@zhengzhenxian thanks! by the way, what do you mean by mat file is not imagenet-vgg-verydeep-16.mat?

**Comment by zhengzhenxian** [comment]
Yeah, I have run the model using the pre-trained vgg-verydeep-16 network and I found it doesn't work so I replace the mat by magenet-vgg-m.mat(http://www.vlfeat.org/matconvnet/models/imagenet-vgg-m.mat). And it works!
Thanks for your great jobs!!

**Comment by silverbottlep** [comment]
@zhengzhenxian I just checked, but I think it should be imagenet-vgg-verydeep-16.mat (http://www.vlfeat.org/matconvnet/models/imagenet-vgg-verydeep-16.mat)?

**Comment by jimmy-dq** [comment]
@silverbottlep  I check that the model used in the code is imagenet-vgg-m.mat, which is also used in the MDNet.

**Comment by silverbottlep** [comment]
@zhengzhenxian @handworker OMG, my fault, CREST used imagenet-vgg-verydeep-16.mat, MDNet used imagenet-vgg-m.mat. I used the same networks for fair comparison. sorry for confusion, I will fix readme
