### ISSUE TITLE
Change the CNN Model

### ISSUE THREAD

**Issue by ahkarami** [silverbottlep/meta_trackers#6]
Dear @silverbottlep,
Thank you for your fantastic work.
I want to change the Base CNN model of your code via another one (_e.g.,_ ResNet18). Do you have any idea that how can I do that?

**Comment by silverbottlep** [comment]
@ahkarami It may require some modifications, but I believe it is not that complicated. I haven't tried other models.

**Comment by he010103** [comment]
@ahkarami  Hello, I think it may be helpful to change the CNN model. Did you successfully change the vgg model to resnet18? Did the resnet18 have a higher accuracy after some modifications? Thanks!

**Comment by ahkarami** [comment]
Dear @he010103,
Unfortunately, I can't change the CNN model of the code.
