### ISSUE TITLE
My interpretation of this project?

### ISSUE THREAD

**Issue by Rheelt** [silverbottlep/meta_trackers#7]
As far as MetaSDNet is concerned, I think meta-learning plays a role in learning good initial parameters in order to adapt the network to the changes in future frames. In addition, since the parameters learned by the meta-learning are used, only the iteration is required once in the first frame and the required samples are reduced, which brings the advantage of speed increase(MDnet iterates 30 times in the first frame, positive sample 500, negative sample 5000). In the tracking of subsequent frames, the same settings as MDNet are used. **The main purpose of the article is to use meta-learning to get a good initialization parameter.** I don't know if my understanding is right?
Thank you for your contribution!

**Comment by silverbottlep** [comment]
Thanks for having interest on this work, and sorry for late response. I was swamped with other works. Yeap, what you described is pretty much right although we also learn learning rates as well.
