### ISSUE TITLE
No such file or directory: '../../dataset/OTB/tb_100.txt'

### ISSUE THREAD

**Issue by hytxx** [silverbottlep/meta_trackers#8]
Traceback (most recent call last):
  File "run_tracker.py", line 405, in <module>
    with open(list_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '../../dataset/OTB/tb_100.txt'

**Comment by guwenning** [comment]
I have the same problem.

**Comment by silverbottlep** [comment]
I think it is because you didn't have dataset
